account/urls.py
from django.urls import path 
from . import views 
from django.contrib.auth import views as auth_views

app_name='account'
urlpatterns = [ 
    path('login/', views.user_login, name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html", success_url="/account/password-change-done/"), name='password_change'), 
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"), name='password_change_done'),
    path('register/', views.register, name='register'),
]

data_platform/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls  import url
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static

app_name = "data_platform"
urlpatterns = [
    url(r'^$', views.index_view.as_view(), name="index"),
    url(r'^accident_list/',views.get_accident_list.as_view(), name="accident_list"),
    url(r'^term_list/',views.get_term_list.as_view(), name="term_list"),
    url(r'^term/(?P<term_id>\d+)$', views.get_term_detail.as_view(), name="term_detail"),
    url(r'^download/',views.get_download.as_view(), name="download"),
    url(r'^model_data/',views.get_model_data.as_view(), name="model_data"),
    url(r'^fm_list/',views.get_fm_list.as_view(), name="fm_list"),
]

rmsdata/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from . import view
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', view.index),
    url(r'^data_platform/', include('data_platform.urls')),
    path('account/', include('account.urls',namespace='account')),
]

data_platform/models.py
from django.db import models
from taggit.managers import TaggableManager

# Create your models here.

#单独建立的用户模型
class  user(models.Model):
  id = models.AutoField(primary_key = True)
  name =  models.CharField(max_length = 100)
  info = models.CharField(max_length = 200, default = "na")


#机型数据模型
class acmodel(models.Model):
    id = models.AutoField(primary_key = True)
    basic_acmodel = models.CharField("基本型号", max_length = 100)
    expanded_acmodel = models.CharField("扩展型号", max_length = 100)
    if_intra_ac = models.BooleanField(default = False)

    class Meta:
        ordering = ('basic_acmodel',)
        verbose_name = '飞机型号'
        verbose_name_plural = '飞机型号'

    def __str__(self):
        return (self.basic_acmodel)
    

#事故数据模型
class accident(models.Model):
  id = models.AutoField(primary_key = True)
  title = models.CharField("标题", max_length=200)
  date = models.DateField("发生时间")
  content = models.TextField("事件描述")
  acmodel = models.ForeignKey(acmodel, on_delete = models.CASCADE)

  def __str__(self):
    return (self.title)
    
#数据来源说明模型    
class data_source(models.Model):
    id = models.AutoField(primary_key = True)
    #The title here represents the name of data source that has a series of data tables, each of them gathered in different time.
    title = models.CharField("title of data table", max_length = 200)
    slug = models.SlugField(max_length=200, unique=True)
    acmodel = models.ForeignKey(acmodel, on_delete = models.CASCADE)
    source_interpretation = models.CharField("Interpretation of the data source", max_length = 300)
                                 
    def __str__(self):
        return (self.title)

#历史数据表模型
class data_address(models.Model):                                                     
    id = models.AutoField(primary_key = True)
    title = models.CharField("download file address", max_length = 200)
    slug = models.SlugField(max_length=200, unique=True)
    date = models.DateField("发生时间")
    data_source = models.ForeignKey(data_source, on_delete = models.CASCADE)
                                                                    
    def __str__(self):
        #resolve the display problem 'Data_addresss' in admin's frontpage, but failed.
        return (self.title+'e')

term/models.py
from django.db import models
from taggit.managers import TaggableManager
from data_platform.models import acmodel

# Create your models here.

#术语所用的分类
class term_category(models.Model):
    id = models.AutoField(primary_key = True)
    name = models.CharField('名称',max_length=200, db_index=True)
    slug = models.SlugField('简称',max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = '术语分类'
        verbose_name_plural = '术语分类'

    def __str__(self):
        return self.name


#缩略语所用的分类
class acr_category(models.Model):
    id = models.AutoField(primary_key = True)
    name = models.CharField('名称',max_length=200, db_index=True)
    slug = models.SlugField('简称',max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = '缩略语分类'
        verbose_name_plural = '缩略语分类'

    def __str__(self):
        return self.name

#术语定义部分内容
class term(models.Model):
    id = models.AutoField(primary_key = True)
    category = models.ForeignKey(term_category, related_name='acr_category', on_delete=models.CASCADE, default = '无分类')
    title = models.CharField("词条", max_length = 200)
    content = models.TextField("词条说明")
    acmodel = models.ForeignKey(acmodel, related_name='适用机型',on_delete = models.CASCADE, limit_choices_to={'if_intra_ac': True})
    tag = TaggableManager("标签",blank=True)
    source = models.TextField("词条来源")

    class Meta:
        ordering = ('title',)
        verbose_name = '术语'
        verbose_name_plural = '术语'

    def __str__(self):
        return (self.title)

#缩略语
class acronym(models.Model):
    id = models.AutoField(primary_key = True)
    category = models.ForeignKey(acr_category, related_name='acr_category', on_delete=models.CASCADE, default = '无分类')
    name = models.CharField("缩略语", max_length = 200)
    full_name = models.TextField("英文全称")
    zh_name = models.TextField("中文全称")
    tag = TaggableManager("标签",blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = '缩略语'
        verbose_name_plural = '缩略语'

    def __str__(self):
        return (self.title)

data_platform/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
#import markdown
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin

from data_platform.models import accident
from term.models import term
from data_platform.models import data_source
from data_platform.models import data_address
from type_data.models import fm

class index_view(ListView):
	template_name = "index.html"
	context_object_name = "text"

	def get_queryset(self):
		now = datetime.datetime.now()
		text={'hello':'Hello world!','name':'J','nowtime':now}
		return(text)


class get_accident_list(LoginRequiredMixin,ListView):
	model = accident
	template_name = "accident_list.html"
	context_object_name =  "accident_list"

		#return context

class get_term_list(LoginRequiredMixin,ListView):
	model = term
	template_name = "term_list.html"
	context_object_name =  "term_list"

class get_term_detail(LoginRequiredMixin,DetailView):
	template_name = "term.html"
	model = term
	context_object_name = "term"
	pk_url_kwarg = 'term_id'

class get_download(ListView):
    template_name = 'download.html'
    context_object_name =  'download'
    
    def get_queryset(self):
        now = datetime.datetime.now()
        text={'hello':'Hello world!','name':'J','nowtime':now}
        return(text)
    
class get_model_data(ListView):
    template_name = 'model_data.html'
    context_object_name =  'model_data'

    def get_queryset(self):
        now = datetime.datetime.now()
        text={'hello':'Hello world!','name':'J','nowtime':now}
        return(text)
#    all_models_dict = {
#         "template_name": "download.html",
#        "context" : {"data_source" : data_source.objects.all(),
#                     "data_address": data_address.objects.all(),
#                    }
#    }
#    context_object_name =  'download'
#    
#    def get_queryset(self):
#        now = datetime.datetime.now()
#        text={'hello':'Hello world!','name':'J','nowtime':now}
#        return(text)


class get_fm_list(LoginRequiredMixin,ListView):
	model = fm
	template_name = "fm_list.html"
	content_object_name =  "fm_list"

term/views.py
from django.shortcuts import render

# Create your views here.

data_platform/templates/foot.html
{% load static %}
<html>
<body>
  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">关于</h4>
          <div class="ui inverted link list">
            <a href="{% url 'data_platform:index' %}" class="item">Sitemap</a>
            <a href="{% url 'data_platform:index' %}" class="item">Contact Us</a>
            <a href="{% url 'data_platform:index' %}" class="item">Religious Ceremonies</a>
            <a href="{% url 'data_platform:index' %}" class="item">Gazebo Plans</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">服务</h4>
          <div class="ui inverted link list">
            <a href="{% url 'data_platform:index' %}" class="item">Banana Pre-Order</a>
            <a href="{% url 'data_platform:index' %}" class="item">DNA FAQ</a>
            <a href="{% url 'data_platform:index' %}" class="item">How To Access</a>
            <a href="{% url 'data_platform:index' %}" class="item">Favorite X-Men</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">页脚</h4>
          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
        </div>
      </div>
    </div>
    <div class="ui center aligned container">
      <div class="ui inverted section divider"></div>
      <div style = "white-space:pre"><b>Copyright </b>© <b>2019-2022 中国商用飞机有限责任公司SIA工作组. </b>All rights reserved.</div>
    </div>
  </div>
  <!--[if lt IE 8]>
  <script src="js/icon-font-ie7.js"></script>
  <script src="js/icon-font-ie7-24.js"></script>
  <![endif]-->
</body>
</html>

data_platform/templates/head.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <title>*****D  A  T  A*****</title>
  <!-- Loading semantic_ui and datatables css files================================-->
  <link href="{% static 'css/semantic.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/datatables.min.css' %}" rel = "stylesheet">
<!--  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">-->
  <!-- Loading semantic_ui and datatables javascript files================================-->
  <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/semantic.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
  
<!--  <script type="text/javascript" src="{% static 'js/dataTables.scroller.min.js"></script>-->
  <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <style type="text/css">
    body {
      background-color: #FFFFFF;
    }
    .ui.menu .item img.logo {
      margin-right: 1.5em;
    }
    .main.container {
      margin-top: 7em;
    }
    .wireframe {
      margin-top: 2em;
    }
    .ui.footer.segment {
      margin: 5em 0em 0em;
      padding: 5em 0em;
    }
    .ui.container > h1 {
      font-size: 3em;
      text-align: center;
      font-weight: normal;
    }
  </style>
</head>
<body>
  <div class="ui fixed primary inverted menu">
    <div class="ui container">
      <a href="{% url 'data_platform:index' %}" class="header item">
        <img class="logo" src="{% static 'logo.png' %}">
          特性Big Data
      </a>
      <div class="ui simple dropdown item">
        型号设计数据 <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item" href="fixed.php#">设计FMEA</a>
          <a class="item" href="fixed.php#">预留</a>
          <div class="divider"></div>
          <a class="item" href="fixed.php#">预留</a>
        </div>
      </div>
      <div class="ui simple dropdown item">
        相似机型数据 <i class="dropdown icon"></i>
        <div class="menu">
          <div class="header">相似机型数据</div>
          <div class="item">
            <i class="dropdown icon"></i>
            运营数据
            <div class="menu">
              <a class="item" href="fixed.php#">链接选项</a>
              <a class="item" href="fixed.php#">链接选项</a>
            </div>
          </div>
          <a href="{% url 'data_platform:fm_list' %}" class="item">相似机型失效模式库</a>
          <div class="divider"></div>
          <div class="header">事故事件</div>
          <a href="{% url 'data_platform:accident_list' %}" class="item">事故事件</a>
          <a class="item" href="fixed.php#">预留</a>
        </div>
      </div>
      <div class="ui simple dropdown item">
        参考数据 <i class="dropdown icon"></i>
        <div class="menu">
          <a href="{% url 'data_platform:term_list' %}" class="item">术语定义</a>
          <a class="item" href="fixed.php#">预留</a>
          <div class="divider"></div>
          <a class="item" href="fixed.php#">预留</a>
        </div>
      </div>
        <a class="item" href="{% url 'data_platform:download' %}">下载</a>
     <div class="ui simple dropdown right item">
          {% if user.is_authenticated %}
          {{ user.username }}<i class="dropdown icon"></i>
          <div class="menu">
            <li><a href="{% url 'account:logout' %}">退出</a></li>
            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
            <li><a href="{% url 'account:logout' %}">个人信息</a></li>
          {% else %}
          游客<i class="dropdown icon"></i>
          <div class="menu">
            <li><a href="{% url 'account:login' %}">登录</a></li>
            <li><a href="{% url 'account:register' %}">注册</a></li>
          {% endif %}
          </div>
          </div>
     </div>
  </div>
</div>
</body>

data_platform/templates/index.html
{% load static %}
{% include "head.html" %}
  <div class="ui main container">
    <h1>特性工程大数据平台</h1>
    <div class="ui text container">
      <p>特性工程大数据平台提供特性工程各专业在型号研制全寿命周期中的数据基础.</p>
      <p>现在是: {{ text.nowtime | date }} </p>
      <p>欢迎...</p>
      <button class = "ui blue button" onclick="location.href='{% url 'data_platform:accident_list' %}'" type = "button">了解更多</button>
    </div>
    <div class="ui raised very padded grid center">
      <div class="two wide column"></div>
      <div class="four wide column">
        <div class="ui raised card">
          <div class="content">
            <div class="header"><a href="{% url 'data_platform:accident_list' %}" class="item">事故事件</a></div>
            <div class="ui test container">相似机型运营数据, 事故事件数据, 及其他参考数据资料<br/><br/><br/></div>
          </div>
          <div class="extra content">
            <div class="right floated author">
              <img class="ui avatar image" src="{% static 'images/login/icon.png' %}"> SIA
            </div>
          </div>
        </div>
      </div>
      <div class="four wide column">
        <div class="ui raised card">
            <div class="content">
                <div class="header"><a href="{% url 'data_platform:model_data' %}" class="item">型号设计</a></div>
              <div class="ui test container">型号设计数据<br/><br/></div>
            </div>
            <div class="extra content">
                <div class="right floated author">
                  <img class="ui avatar image" src="{% static 'images/login/icon.png' %}"> SIA
                </div>
          </div>
        </div>
      </div>
      <div class="four wide column">
        <div class="ui raised card">
          <div class="content">
            <div class="header"><a href="{% url 'data_platform:term_list' %}" class="item">术语定义</a></div>
            <div class="ui test container">型号常用术语, 定义, 缩略语<br/><br/><br/><br/></div>
            <div class="description">
              <p></p>
            </div>
          </div>
          <div class="extra content">
            <div class="right floated author">
              <img class="ui avatar image" src="{% static 'images/login/icon.png' %}"> SIA
            </div>
          </div>
        </div>
      </div>
      <div class="two wide column"></div>
    </div>
    <p><strong class="Afghanistan flag"> </strong></p>
  </div>
{% include "foot.html" %}
<!--以下是只在本页面中适用的css和js等内容-->
<style type="text/css">
  .ui.text.container  {
    text-align: center;
    font-weight: normal;
  }
</style>

data_platform/templates/page.html
{% load static %}
{% include "head.html" %}

<div class="ui main text container">
  <div>
  <h3 class="ui header">
    文章列表
  </h3>
  {% for article in article_list %}
  <div class="blog-post">
    <h2>
      <a class="text-dark" href="{% url 'blog:detail' article.id %}">{{article.title}}</a>
    </h2>
    <hr>
    <div>
      <p>{{ article.content | striptags |truncatewords:20}}</p>
    </div>
  </div>
  {% endfor %}
  </div>
</div>

{% include "foot.html" %}

data_platform/templates/search_form.html
{% include "head.html" %}
      <div class="container bs-docs-container">
        <div class="demo-headline">
          <h1 class="demo-logo">
            <div class="logo"></div>
            Thelalasis
            <small>马彪的个人主页</small>
          </h1>
        </div> <!-- /demo-headline -->

        <!-- Static navbar -->
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
          <form action="/search" method="post">
            {% csrf_token %}
            <input type="text" name="q">
            <input type="submit" value="搜索">
          </form>
          <p>{{rlt}}</p>
          <p>{{ttt}}</p>
        </div>
      </div> <!-- /container -->
{% include "foot.html" %}

data_platform/templates/search_result.html
{% include "head.html" %}
      <div class="container bs-docs-container">
        <div class="demo-headline">
          <h1 class="demo-logo">
            <div class="logo"></div>
            Thelalasis
            <small>马彪的个人主页</small>
          </h1>
        </div> <!-- /demo-headline -->

        <!-- Static navbar -->
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
          <p>{{msg}}</p>
        </div>
      </div> <!-- /container -->
{% include "foot.html" %}

data_platform/templates/term.html
{% load static %}
{% include "head.html" %}
<div class="ui main text container"> 
    <div class="ui grid">
        <div class="four wide column left floated">
            <div class="ui animated button" tabindex="0">
              <div class="visible content">返回</div>
              <div class="hidden content">
                <a href="{% url 'data_platform:term_list' %}"><i class="left arrow icon"></i></a>
              </div>
            </div>
        </div>
        <div class="eight wide column right floated">
          <h2 class="ui header">
            <div class="column"><i class="book icon"></i>{{term.title}}</div>
          </h2>
        </div>
        <div class="ten wide column">
            {% for tag in term.tag.all %}
            <a class="ui teal tag label">{{tag}}</a>
            {% endfor %}
        </div>
    </div> 

    <div class="ui divider"></div>
    <div class="ui raised very padded text container segment">
      <h3>相关型号</h3>
      <button class="ui inverted red button">{{term.acmodel}}</button>
    </div>
    <div class="ui raised very padded text container segment">
      <h3>词条解释</h3>
      <p>{{term.content | safe}}</p>
    </div>
  </div>
  <div class="ui raised very padded text container segment">
      <h3>词条来源</h3>
      <p>{{term.source | safe}}</p>
    </div>
{% include "foot.html" %}

data_platform/templates/term_list.html
{% load static %}
{% include "head.html" %}
<body>
    <div class="ui invisible inverted left vertical sidebar menu">
            <a class="item">
                <img class="ui avatar image" src="{% static 'images/icons/imac.svg' %}">
              &#8195;&#8194;监控面板
            </a>
            <a class="item">
                <img class="ui avatar image" src="{% static 'images/icons/clipboard.svg' %}">
              &#8195;&#8194;问题管理
            </a>
            <div class="item">
                <img class="ui avatar image" src="{% static 'images/icons/goal.svg' %}">
                  &#8195;&#8194;我的任务
                <div class="menu">
                      <a class="item">&#8195;&#8195;&#8195;&#8195;&#8195;待处理的任务</a>
                      <a class="item">&#8195;&#8195;&#8195;&#8195;&#8195;已处理的任务</a>
                </div>
            </div>
    </div>

    <div class="ui main container">
        <div class="ui column">
            <div class = 'row'>
                <div class="pusher">
                   <div id = "toggle" class="ui labeled icon button">
                    <i class = "sidebar icon"></i>
                    Menu
                   </div>
                </div>
            </div>

            <div class="item">
                <h2 class = "ui center aligned header">术语定义表</h2>
            </div>
        </div>

        <div class="ui basic segment pushable">
            <div class="ui basic segment">
                <button class="ui new blue button">
                    <i class="file icon"></i>
                    新建
                </button>
                <button class="ui renewal button">
                    <i class="redo icon"></i>
                    刷新
                </button>
                <button class="ui download button">
                    <i class="download icon"></i>
                    下载
                </button>
                
                <!--reserve for some room in between-->
                <p></p>
                
              <table id="accident" class="ui striped table">
                  <thead>
                  <tr>
                    <th>术语</th>
                    <th>适用机型</th>
                    <th>术语说明</th>
                  </tr>
                  </thead>
                  <tfoot>
                  <tr>
                    <th>术语</th>
                    <th>适用机型</th>
                    <th>术语说明</th>
                  </tr>
                  </tfoot>
                  <tbody>
                      {% for term in term_list %}
                          <tr>
                            <td><a class="text-dark" href="{% url 'data_platform:term_detail' term.id %}">{{term.title}}</a></td>
                            <td>{{term.acmodel}}</td>
                            <td>{{term.content | striptags |truncatewords:20}}</td>
                          </tr>
                      {% endfor %}
                  </tbody>
              </table>

              <p>
                <button id="addRow">添加行</button>
                <button id="delRow">删除选中的行</button>
              </p>
            </div>
        </div>
    </div>    
</body>
{% include "foot.html" %}
<!-- 脚本部分用来处理表格样式等内容, 整个datatables用两个部分来控制, table部分控制数据和交互, script部分控制展试, 分页和搜索等功能-->
 <!-- Js for datatables. -->
<script type="text/javascript">
    $(document).ready(function() {
      var table = $('#accident').DataTable({
          "language": {
            "sProcessing": "处理中...",
            "sLengthMenu": "显示 _MENU_ 项结果",
            "sZeroRecords": "没有匹配结果",
            "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
            "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
            "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
            "sInfoPostFix": "",
            "sSearch": "搜索:",
            "sUrl": "",
            "sEmptyTable": "表中数据为空",
            "sLoadingRecords": "载入中...",
            "sInfoThousands": ",",
            "oPaginate": {
                "sFirst": "首页",
                "sPrevious": "上页",
                "sNext": "下页",
                "sLast": "末页"
            },
            "oAria": {
                "sSortAscending": ": 以升序排列此列",
                "sSortDescending": ": 以降序排列此列"
            }
          }
     });
        
    //分列查找内容
    // Setup - add a text input to each footer cell
    $('#accident tfoot th').each( function () {
        var title = $('#accident thead th').eq( $(this).index() ).text();
        $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
    });
        
    // Apply the search
    table.columns().eq( 0 ).each( function ( colIdx ) {
        $( 'input', table.column( colIdx ).footer() ).on( 'keyup change', function () {
            table.column( colIdx ).search( this.value ).draw();
        });
    });
    //将tfoot挪到表格上方
    $('#accident tfoot tr').appendTo('#accident thead');

    //高亮鼠标停留的行和列
    var lastIdx = null;
    $('#accident tbody')
        .on( 'mouseover', 'td', function () {
            var colIdx = table.cell(this).index().column;
            if ( colIdx !== lastIdx ) {
                $( table.cells().nodes() ).removeClass( 'highlight' );
                $( table.column( colIdx ).nodes() ).addClass( 'highlight' );
            }
        } )
        .on( 'mouseleave',  function () {
            $( table.cells().nodes() ).removeClass( 'highlight' );
        } );
        
 
    } );
</script>

<!-- css for datatables. 设置高亮style-->
<style type="text/css">
    .highlight {
        background-color: skyblue!important;
    }
</style>

<script type="text/javascript"> 
    $('#toggle').click(function(){
        $('.ui.sidebar').sidebar('toggle');
    });
</script>